name: Build npm release

trigger:
  - master

jobs:
  - template: build/platform-pipeline.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04

  - template: build/platform-pipeline.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.13

  - template: build/platform-pipeline.yml
    parameters:
      platform: Windows
      vmImage: vs2017-win2016

  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows
    pool:
      vmImage: macOS-10.13
      demands: node.js
    steps:
      - template: utils/use-node.yml
      - template: cross-release.yml
