parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  CACHE_FOLDER: $(Pipeline.Workspace)/cache
  AZP_CACHING_TAR: false
  ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      AZP_CACHING_TAR: ${{ parameters.AZP_CACHING_TAR }}
      ESY__CACHE_INSTALL_PATH: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      CACHE_FOLDER: ${{ parameters.CACHE_FOLDER }}

    steps:
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - template: utils/cache.yml
     # - template: utils/restore-build-cache.yml
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - template: utils/create-docs.yml
      - script: "esy test"
        displayName: "Test command"
      - script: "esy release"
        displayName: "esy release"
     # - template: utils/publish-build-cache.yml
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: ${{ parameters.platform }}"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: ${{ parameters.platform }}
      - template: utils/prepare-cache.yml
