parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      ESY__CACHE_INSTALL_PATH: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps: 
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - template: utils/restore-build-cache.yml
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - template: utils/create-docs.yml
      - script: "esy test"
        displayName: "Test command"
      - script: "esy release"
        displayName: "esy release"
      - template: utils/publish-build-cache.yml
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: ${{ parameters.platform }}"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: ${{ parameters.platform }}
