parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  ESY__PREFIX: $(Pipeline.Workspace)/.esy
  AZP_CACHING_TAR: true
  INSTALL_PADDING: "/3_______________________________________________/i"

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      ESY__PREFIX: ${{ parameters.ESY__PREFIX }}
      AZP_CACHING_TAR: ${{ parameters.AZP_CACHING_TAR }}

    steps:
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - template: cache.yml
        parameters:
          ESY_PREFIX: ${{ parameters.ESY__PREFIX }}
          INSTALL_PADDING: ${{ parameters.INSTALL_PADDING }}
     # - template: utils/restore-build-cache.yml
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - template: utils/create-docs.yml
      - script: "esy test"
        displayName: "Test command"
      - script: "esy release"
        displayName: "esy release"
     # - template: utils/publish-build-cache.yml
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: ${{ parameters.platform }}"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: ${{ parameters.platform }}
