parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  STAGING_DIRECTORY: $(Build.StagingDirectory)
  STAGING_DIRECTORY_UNIX: $(Build.StagingDirectory)

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      STAGING_DIRECTORY: ${{ parameters.STAGING_DIRECTORY }}
      STAGING_DIRECTORY_UNIX: ${{ parameters.STAGING_DIRECTORY_UNIX }}

/Users/jwalke/.esy/3
/Users/jwalke/.esy/3__________________________________________________________________
      

    steps: 
      # reate a variable
      - bash: |
          HOME_ESY3="$HOME/.esy/3"
          HOME_ESY3_LEN=${#HOME_ESY}
          $SIXTY_SIX="66"
          $NUM_UNDERS=echo "$(($SIXTY_SIX+$HOME_ESY3_LEN))"
          $UNDERS="$(seq -s_ ${SIXTY_SIX}|tr -d '[:digit:]')"
          ESY__CACHE_INSTALL_PATH=${HOME_ESY3}${UNDERS}/i
          echo "##vso[task.setvariable variable=esy__cache_install_path]$ESY__CACHE_INSTALL_PATH"
      - bash: echo Publishing Build Cache From $(esy__cache_install_path)
        displayName: 'Debugging ESY__CACHE_INSTALL_PATH var'
      - bash: env
        displayName: "Print environment"
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - template: utils/restore-build-cache.yml
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - template: utils/create-docs.yml
      - script: "esy test"
        displayName: "Test command"
      - script: "esy release"
        displayName: "esy release"
      - template: utils/publish-build-cache.yml
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: ${{ parameters.platform }}"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: ${{ parameters.platform }}
