name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@d504f1813939f7821ce4c8ed855ddfcf8b390761
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
      - uses: esy/github-action@444f3afcddbe04e2c5994f3e3624001dae88d539
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          prepare-npm-artifacts-mode: true
      - name: Test
        run: esy test

      - name: Build docs
        run: esy doc

  bundle:
    runs-on: macos-latest
    steps:
      - uses: esy/github-action@baf273e85096dfd01f6f7c6ac83e63c86e2b719a
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          bundle-npm-artifacts-mode: true
