name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
      - uses: actions/checkout@v2.2.0
      - name: Install esy
        run: npm install -g esy
        
      - name: Try to restore install cache
        uses: actions/cache@v2
        with:
          path: ~/.esy/source
          key: source-${{ hashFiles('**/index.json') }}

      - name: Install
        run: esy install

      - name: Print esy cache
        uses: actions/github-script@v2
        id: print_esy_cache
        with:
          script: |
            const path = require('path')
            const scriptPath = path.resolve('.github/workflows/print_esy_cache.js')
            require(scriptPath)(core)

      - name: Try to restore build cache
        id: deps-cache-macos
        uses: actions/cache@v2
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: build-${{ matrix.os }}-

      - name: Build
        run: |
          esy build
          # Cleanup build cache in case dependencies have changed
          esy cleanup .

      - name: Test
        run: esy test

      - name: Build docs
        run: esy doc
