name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@d504f1813939f7821ce4c8ed855ddfcf8b390761
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
      - uses: esy/github-action@9fe0fe3a51d1f5db8a44f2bb5908327708977af3
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          prepare-npm-artifacts-mode: true
      - name: Test
        run: esy test

      - name: Build docs
        run: esy doc
