name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    outputs:
      linux-x64: ${{ steps.prepare-npm-artifacts.ouputs.linux-x64 }}
      windows-x64: ${{ steps.prepare-npm-artifacts.ouputs.windows-x64 }}
      darwin-x64: ${{ steps.prepare-npm-artifacts.ouputs.darwin-x64 }}
      darwin-arm64: ${{ steps.prepare-npm-artifacts.ouputs.darwin-arm64 }}
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@d504f1813939f7821ce4c8ed855ddfcf8b390761
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
      - uses: esy/github-action@444f3afcddbe04e2c5994f3e3624001dae88d539
        id: prepare-npm-artifacts
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          prepare-npm-artifacts-mode: true
      - name: Test
        run: esy test

      - name: Build docs
        run: esy doc

  bundle:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: esy/github-action@0534a6f978a140eb2d157e27f8e825b2a3a35c30
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          bundle-npm-artifacts-mode: true
          artifact-names: '[ "npm-release-darwin-arm64", "npm-release-linux-x64", "npm-release-win32-x64" ]'
